beat:
  build: .
  environment:
    - LIBBEAT_PATH=/go/src/github.com/rwdial/beats/libbeat
    # Puts build dir outside of shared file system to prevent issues
    # This means artifacts are not shared locally
    - BUILD_DIR=/tmp/build
  volumes:
    - ..:/go/src/github.com/rwdial/beats/
  working_dir: /go/src/github.com/rwdial/beats/packetbeat
